# Generated by Django 3.1.2 on 2020-10-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='profile',
            new_name='user',
        ),
    ]
