# Generated by Django 3.1.2 on 2020-10-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0017_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='likes',
            new_name='liked',
        ),
    ]
